default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  timeout: 5000
  username: pooya


development:
  <<: *default
  database: recomify_development

test:
  <<: *default
  database: recomify_test

production:
  <<: *default
  database: recomfiy_production
